// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class email_updates1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(email_updates1));
        
        string IMigrationMetadata.Id
        {
            get { return "201409302030105_email_updates-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
