// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class permissionsetkey_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(permissionsetkey_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201409222215400_permissionset-key_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
