// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initialformbuilder_FormFormCloseMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialformbuilder_FormFormCloseMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201407301835160_initial-formbuilder_Form--FormCloseMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
