// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Email_ContactReportKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Email_ContactReportKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201409171343294_Email_ContactReportKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
