// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Company_TokenAndKey_MinusParentCompanybool_AddParentCompanyCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Company_TokenAndKey_MinusParentCompanybool_AddParentCompanyCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201410062114469_Company_TokenAndKey_MinusParentCompany-bool_AddParentCompany-Company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
