// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class seatingholdinterval : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seatingholdinterval));
        
        string IMigrationMetadata.Id
        {
            get { return "201411190227124_seating-holdinterval"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
