// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class removeCompanyAudience_DefaultComponentOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeCompanyAudience_DefaultComponentOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201411192045096_removeCompany-Audience_DefaultComponentOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
