// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Registrant_propStatusDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Registrant_propStatusDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201409191720149_Registrant_prop-StatusDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
