// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class remove_CCNumber_transactionDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_CCNumber_transactionDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201408141657203_remove_CCNumber_transactionDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
