// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class reportData_companyKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reportData_companyKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201506101914303_reportData_companyKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
