// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class IXFormKeywithEmailwithTypeOnRegistrant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IXFormKeywithEmailwithTypeOnRegistrant));
        
        string IMigrationMetadata.Id
        {
            get { return "201504210407074_IX-FormKey-with-Email-with-Type-OnRegistrant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
