// <auto-generated />
namespace RSToolKit.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class contactsregadd_enumData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contactsregadd_enumData));
        
        string IMigrationMetadata.Id
        {
            get { return "201501271849086_contacts-regadd_enumData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
